# ###########################################################
# Do make changes here.

version: "3"

services:
  con1:
    image: test1
    build: .
    networks:
      - test1
    ports:
      - "8000:80"


  con2:
    image: test2
    build: .
    networks:
      - test1
    ports:
      - "8001:80"

networks:
  test1:

