# ############################################################
# DO NOT CHANGE THIS FILE.
#

up start:
	docker compose up -d

test:
	# Do make changes inside "./test.bash".
	#
	bash ./test.bash

stop:
	docker compose stop
