# Generated by Django 3.2.12 on 2023-02-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('card_expiry', models.DateField()),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_cheeses', models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Vegan', 'Vegan'), ('Low Fat', 'Low Fat')], default='Mozzarella', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCrust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_crusts', models.CharField(choices=[('Normal', 'Normal'), ('Thin', 'Thin'), ('Thick', 'Thick'), ('Gluten Free', 'Gluten Free')], default='Normal', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_sauces', models.CharField(choices=[('Tomato', 'Tomato'), ('BBQ', 'BBQ'), ('Curry', 'Curry')], default='Tomato', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_sizes', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Small', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_toppings', models.CharField(choices=[('pepperoni', 'pepperoni'), ('chicken', 'chicken'), ('ham', 'ham'), ('pineapple', 'pineapple'), ('peppers', 'peppers'), ('mushrooms', 'mushrooms'), ('onions', 'Broccoli')], default='Pepperoni', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_cheeses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzacheese')),
                ('pizza_crusts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzacrust')),
                ('pizza_sauces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzasauce')),
                ('pizza_sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzasize')),
                ('pizza_toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzatoppings')),
            ],
        ),
    ]
