# Generated by Django 3.2.12 on 2023-02-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='card_expiry',
            field=models.TextField(),
        ),
    ]
