# Generated by Django 3.2.12 on 2023-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_customerdetails_card_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='card_expiry',
            field=models.DateField(),
        ),
    ]
